// Code generated by protoc-gen-liquidproto. DO NOT EDIT.
// versions:
// 	protoc-gen-liquidproto v0.1.0
// 	protoc                 v7.35.1
// source: xetcas/v1/bridge.proto

package xetcasv1

import (
	fmt "fmt"
	liquidproto "github.com/candacelabs/candacelib/liquidproto"
	regexp "regexp"
)

var (
	_liquidLfsObjectSpecOidRe0 = regexp.MustCompile("^[0-9a-f]{64}$")
)

// ValidateLfsObjectSpec validates Liquid Proto field predicates.
func ValidateLfsObjectSpec(message *LfsObjectSpec) error {
	if message == nil {
		return fmt.Errorf("ValidateLfsObjectSpec: nil *LfsObjectSpec")
	}
	if !(len(message.Oid) == 64 && _liquidLfsObjectSpecOidRe0.MatchString(message.Oid)) {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.LfsObjectSpec",
			Field:     "oid",
			Predicate: "len(this) == 64 && matches(this, \"^[0-9a-f]{64}$\")",
			Value:     message.Oid,
		}
	}
	return nil
}

// ValidateLfsBatchRequest validates Liquid Proto field predicates.
func ValidateLfsBatchRequest(message *LfsBatchRequest) error {
	if message == nil {
		return fmt.Errorf("ValidateLfsBatchRequest: nil *LfsBatchRequest")
	}
	if !(message.Operation == "upload" || message.Operation == "download") {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.LfsBatchRequest",
			Field:     "operation",
			Predicate: "this == \"upload\" || this == \"download\"",
			Value:     message.Operation,
		}
	}
	if !(len(message.HashAlgo) == 0 || message.HashAlgo == "sha256") {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.LfsBatchRequest",
			Field:     "hash_algo",
			Predicate: "len(this) == 0 || this == \"sha256\"",
			Value:     message.HashAlgo,
		}
	}
	return nil
}

// ValidateLfsAction validates Liquid Proto field predicates.
func ValidateLfsAction(message *LfsAction) error {
	if message == nil {
		return fmt.Errorf("ValidateLfsAction: nil *LfsAction")
	}
	if !(len(message.Href) >= 1) {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.LfsAction",
			Field:     "href",
			Predicate: "len(this) >= 1",
			Value:     message.Href,
		}
	}
	return nil
}

// ValidateLfsBatchResponse validates Liquid Proto field predicates.
func ValidateLfsBatchResponse(message *LfsBatchResponse) error {
	if message == nil {
		return fmt.Errorf("ValidateLfsBatchResponse: nil *LfsBatchResponse")
	}
	if !(message.Transfer == "xet" || message.Transfer == "basic") {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.LfsBatchResponse",
			Field:     "transfer",
			Predicate: "this == \"xet\" || this == \"basic\"",
			Value:     message.Transfer,
		}
	}
	return nil
}

// ValidateCasTokenInfo validates Liquid Proto field predicates.
func ValidateCasTokenInfo(message *CasTokenInfo) error {
	if message == nil {
		return fmt.Errorf("ValidateCasTokenInfo: nil *CasTokenInfo")
	}
	if !(len(message.CasUrl) >= 1) {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.CasTokenInfo",
			Field:     "cas_url",
			Predicate: "len(this) >= 1",
			Value:     message.CasUrl,
		}
	}
	if !(len(message.AccessToken) >= 1) {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.CasTokenInfo",
			Field:     "access_token",
			Predicate: "len(this) >= 1",
			Value:     message.AccessToken,
		}
	}
	return nil
}
