// Bridge contracts: the minimal Git LFS surface that connects `git push` to
// the Xet CAS transfer contract, plus the token bootstrap message.
//
// The client side is stock git-lfs plus git-xet (xet-core's LFS custom
// transfer agent, registered as transfer "xet"). git-xet performs uploads
// over the Xet protocol; downloads deliberately fall back to git-lfs basic
// transfer, so the server reconstructs whole files and serves them by
// sha256 oid.
//
// Wire mapping: Git LFS batch bodies are JSON with the exact field names
// below (Content-Type application/vnd.git-lfs+json). Empty optional
// sub-messages (actions, error, ref) are omitted from JSON, not emitted as
// null — codegen marks them skip-if-empty. CasTokenInfo is the one message
// in this package whose JSON is camelCase (casUrl, accessToken, exp),
// matching xet-core's CasJWTInfo.
//
// Endpoints codified here:
//
//   POST {repo}.git/info/lfs/objects/batch   LfsBatchRequest -> LfsBatchResponse
//   GET  <token route chosen by the server>  -> CasTokenInfo
//     (handed to git-xet as the batch action href; also called by hf_xet
//      style clients as token_refresh_url)
//   GET  <download href chosen by the server> -> reconstructed file bytes
//     (git-lfs basic transfer; body is the whole file whose sha256 is the
//      requested oid)
//
// For an upload batch whose "transfers" includes "xet", the server answers
// transfer "xet" and each object's upload action carries:
//   href   = the token refresh route (git-xet GETs it when the token
//            expires mid-session; response is CasTokenInfo)
//   header = X-Xet-Cas-Url (CAS endpoint base, no trailing slash),
//            X-Xet-Access-Token (opaque bearer token),
//            X-Xet-Token-Expiration (decimal unix seconds, as a string),
//            X-Xet-Session-Id (optional session correlation id)
// Exact header casing is mandatory: git-xet does exact-case map lookups.
// For download batches the server must NOT select "xet" (git-xet rejects
// download init); it answers basic transfer with a download href.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: xetcas/v1/bridge.proto

package xetcasv1

import (
	_ "github.com/candacelabs/candacelib/liquidproto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LfsRef identifies the ref being pushed, when git-lfs supplies it.
type LfsRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LfsRef) Reset() {
	*x = LfsRef{}
	mi := &file_xetcas_v1_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LfsRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LfsRef) ProtoMessage() {}

func (x *LfsRef) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LfsRef.ProtoReflect.Descriptor instead.
func (*LfsRef) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *LfsRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// LfsObjectSpec names one object in a batch request.
type LfsObjectSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// git-lfs oid: SHA-256 of the file content, 64 lowercase hex chars
	// (plain byte-order hex, unlike xet-core hash hex).
	Oid           string `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`
	Size          uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LfsObjectSpec) Reset() {
	*x = LfsObjectSpec{}
	mi := &file_xetcas_v1_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LfsObjectSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LfsObjectSpec) ProtoMessage() {}

func (x *LfsObjectSpec) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LfsObjectSpec.ProtoReflect.Descriptor instead.
func (*LfsObjectSpec) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *LfsObjectSpec) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *LfsObjectSpec) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// LfsBatchRequest is the subset of the Git LFS batch API request the server
// consumes.
type LfsBatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "upload" or "download".
	Operation string `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	// Transfer adapters the client supports, e.g. ["xet", "basic"]. Absent
	// means ["basic"].
	Transfers []string         `protobuf:"bytes,2,rep,name=transfers,proto3" json:"transfers,omitempty"`
	Ref       *LfsRef          `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	Objects   []*LfsObjectSpec `protobuf:"bytes,4,rep,name=objects,proto3" json:"objects,omitempty"`
	// git-lfs sends "sha256"; anything else is rejected.
	HashAlgo      string `protobuf:"bytes,5,opt,name=hash_algo,json=hashAlgo,proto3" json:"hash_algo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LfsBatchRequest) Reset() {
	*x = LfsBatchRequest{}
	mi := &file_xetcas_v1_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LfsBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LfsBatchRequest) ProtoMessage() {}

func (x *LfsBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LfsBatchRequest.ProtoReflect.Descriptor instead.
func (*LfsBatchRequest) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *LfsBatchRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *LfsBatchRequest) GetTransfers() []string {
	if x != nil {
		return x.Transfers
	}
	return nil
}

func (x *LfsBatchRequest) GetRef() *LfsRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *LfsBatchRequest) GetObjects() []*LfsObjectSpec {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *LfsBatchRequest) GetHashAlgo() string {
	if x != nil {
		return x.HashAlgo
	}
	return ""
}

// LfsAction tells the client how to perform one operation on one object.
type LfsAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Href  string                 `protobuf:"bytes,1,opt,name=href,proto3" json:"href,omitempty"`
	// Headers the client must attach (for transfer "xet": the X-Xet-* set
	// documented above, consumed verbatim by git-xet).
	Header map[string]string `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Seconds of validity, advisory.
	ExpiresIn     uint64 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LfsAction) Reset() {
	*x = LfsAction{}
	mi := &file_xetcas_v1_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LfsAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LfsAction) ProtoMessage() {}

func (x *LfsAction) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LfsAction.ProtoReflect.Descriptor instead.
func (*LfsAction) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *LfsAction) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *LfsAction) GetHeader() map[string]string {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LfsAction) GetExpiresIn() uint64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// LfsObjectError reports a per-object failure inside a 200 batch response.
type LfsObjectError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Git LFS convention: 404 object missing, 422 validation error.
	Code          uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LfsObjectError) Reset() {
	*x = LfsObjectError{}
	mi := &file_xetcas_v1_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LfsObjectError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LfsObjectError) ProtoMessage() {}

func (x *LfsObjectError) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LfsObjectError.ProtoReflect.Descriptor instead.
func (*LfsObjectError) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *LfsObjectError) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LfsObjectError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// LfsBatchObject is one object's entry in a batch response. An upload entry
// with no actions means "server already has it, skip". Exactly one of
// actions/error is populated when work or failure is being signaled.
type LfsBatchObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Oid   string                 `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`
	Size  uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// Whether href/header already embed authorization; suppresses git-lfs
	// credential prompts on the action requests.
	Authenticated bool `protobuf:"varint,3,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	// Keyed by action name: "upload", "download" (a "verify" action is
	// deliberately never emitted by this server).
	Actions       map[string]*LfsAction `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         *LfsObjectError       `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LfsBatchObject) Reset() {
	*x = LfsBatchObject{}
	mi := &file_xetcas_v1_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LfsBatchObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LfsBatchObject) ProtoMessage() {}

func (x *LfsBatchObject) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LfsBatchObject.ProtoReflect.Descriptor instead.
func (*LfsBatchObject) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *LfsBatchObject) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *LfsBatchObject) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *LfsBatchObject) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *LfsBatchObject) GetActions() map[string]*LfsAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *LfsBatchObject) GetError() *LfsObjectError {
	if x != nil {
		return x.Error
	}
	return nil
}

// LfsBatchResponse is the server's batch answer.
type LfsBatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chosen transfer adapter: "xet" for uploads negotiated with git-xet,
	// "basic" otherwise (including every download batch).
	Transfer      string            `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	Objects       []*LfsBatchObject `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	HashAlgo      string            `protobuf:"bytes,3,opt,name=hash_algo,json=hashAlgo,proto3" json:"hash_algo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LfsBatchResponse) Reset() {
	*x = LfsBatchResponse{}
	mi := &file_xetcas_v1_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LfsBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LfsBatchResponse) ProtoMessage() {}

func (x *LfsBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LfsBatchResponse.ProtoReflect.Descriptor instead.
func (*LfsBatchResponse) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *LfsBatchResponse) GetTransfer() string {
	if x != nil {
		return x.Transfer
	}
	return ""
}

func (x *LfsBatchResponse) GetObjects() []*LfsBatchObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *LfsBatchResponse) GetHashAlgo() string {
	if x != nil {
		return x.HashAlgo
	}
	return ""
}

// CasTokenInfo is the token bootstrap/refresh response body. JSON is
// camelCase: {"casUrl": ..., "exp": ..., "accessToken": ...} — exactly
// xet-core's CasJWTInfo. exp is unix seconds.
type CasTokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CasUrl        string                 `protobuf:"bytes,1,opt,name=cas_url,json=casUrl,proto3" json:"cas_url,omitempty"`
	Exp           uint64                 `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CasTokenInfo) Reset() {
	*x = CasTokenInfo{}
	mi := &file_xetcas_v1_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CasTokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasTokenInfo) ProtoMessage() {}

func (x *CasTokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasTokenInfo.ProtoReflect.Descriptor instead.
func (*CasTokenInfo) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *CasTokenInfo) GetCasUrl() string {
	if x != nil {
		return x.CasUrl
	}
	return ""
}

func (x *CasTokenInfo) GetExp() uint64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *CasTokenInfo) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

var File_xetcas_v1_bridge_proto protoreflect.FileDescriptor

const file_xetcas_v1_bridge_proto_rawDesc = "" +
	"\n" +
	"\x16xetcas/v1/bridge.proto\x12\x11candace.xetcas.v1\x1a\x1fliquidproto/v1/refinement.proto\"\x1c\n" +
	"\x06LfsRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"o\n" +
	"\rLfsObjectSpec\x12J\n" +
	"\x03oid\x18\x01 \x01(\tB8\x92\x82\x194\n" +
	"2len(this) == 64 && matches(this, \"^[0-9a-f]{64}$\")R\x03oid\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\"\xab\x02\n" +
	"\x0fLfsBatchRequest\x12J\n" +
	"\toperation\x18\x01 \x01(\tB,\x92\x82\x19(\n" +
	"&this == \"upload\" || this == \"download\"R\toperation\x12\x1c\n" +
	"\ttransfers\x18\x02 \x03(\tR\ttransfers\x12+\n" +
	"\x03ref\x18\x03 \x01(\v2\x19.candace.xetcas.v1.LfsRefR\x03ref\x12:\n" +
	"\aobjects\x18\x04 \x03(\v2 .candace.xetcas.v1.LfsObjectSpecR\aobjects\x12E\n" +
	"\thash_algo\x18\x05 \x01(\tB(\x92\x82\x19$\n" +
	"\"len(this) == 0 || this == \"sha256\"R\bhashAlgo\"\xd1\x01\n" +
	"\tLfsAction\x12(\n" +
	"\x04href\x18\x01 \x01(\tB\x14\x92\x82\x19\x10\n" +
	"\x0elen(this) >= 1R\x04href\x12@\n" +
	"\x06header\x18\x02 \x03(\v2(.candace.xetcas.v1.LfsAction.HeaderEntryR\x06header\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x04R\texpiresIn\x1a9\n" +
	"\vHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x0eLfsObjectError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb9\x02\n" +
	"\x0eLfsBatchObject\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\tR\x03oid\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12$\n" +
	"\rauthenticated\x18\x03 \x01(\bR\rauthenticated\x12H\n" +
	"\aactions\x18\x04 \x03(\v2..candace.xetcas.v1.LfsBatchObject.ActionsEntryR\aactions\x127\n" +
	"\x05error\x18\x05 \x01(\v2!.candace.xetcas.v1.LfsObjectErrorR\x05error\x1aX\n" +
	"\fActionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.candace.xetcas.v1.LfsActionR\x05value:\x028\x01\"\xb0\x01\n" +
	"\x10LfsBatchResponse\x12B\n" +
	"\btransfer\x18\x01 \x01(\tB&\x92\x82\x19\"\n" +
	" this == \"xet\" || this == \"basic\"R\btransfer\x12;\n" +
	"\aobjects\x18\x02 \x03(\v2!.candace.xetcas.v1.LfsBatchObjectR\aobjects\x12\x1b\n" +
	"\thash_algo\x18\x03 \x01(\tR\bhashAlgo\"\x88\x01\n" +
	"\fCasTokenInfo\x12-\n" +
	"\acas_url\x18\x01 \x01(\tB\x14\x92\x82\x19\x10\n" +
	"\x0elen(this) >= 1R\x06casUrl\x12\x10\n" +
	"\x03exp\x18\x02 \x01(\x04R\x03exp\x127\n" +
	"\faccess_token\x18\x03 \x01(\tB\x14\x92\x82\x19\x10\n" +
	"\x0elen(this) >= 1R\vaccessTokenB4Z2github.com/candacelabs/xetcas/go/xetcasv1;xetcasv1b\x06proto3"

var (
	file_xetcas_v1_bridge_proto_rawDescOnce sync.Once
	file_xetcas_v1_bridge_proto_rawDescData []byte
)

func file_xetcas_v1_bridge_proto_rawDescGZIP() []byte {
	file_xetcas_v1_bridge_proto_rawDescOnce.Do(func() {
		file_xetcas_v1_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xetcas_v1_bridge_proto_rawDesc), len(file_xetcas_v1_bridge_proto_rawDesc)))
	})
	return file_xetcas_v1_bridge_proto_rawDescData
}

var file_xetcas_v1_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_xetcas_v1_bridge_proto_goTypes = []any{
	(*LfsRef)(nil),           // 0: candace.xetcas.v1.LfsRef
	(*LfsObjectSpec)(nil),    // 1: candace.xetcas.v1.LfsObjectSpec
	(*LfsBatchRequest)(nil),  // 2: candace.xetcas.v1.LfsBatchRequest
	(*LfsAction)(nil),        // 3: candace.xetcas.v1.LfsAction
	(*LfsObjectError)(nil),   // 4: candace.xetcas.v1.LfsObjectError
	(*LfsBatchObject)(nil),   // 5: candace.xetcas.v1.LfsBatchObject
	(*LfsBatchResponse)(nil), // 6: candace.xetcas.v1.LfsBatchResponse
	(*CasTokenInfo)(nil),     // 7: candace.xetcas.v1.CasTokenInfo
	nil,                      // 8: candace.xetcas.v1.LfsAction.HeaderEntry
	nil,                      // 9: candace.xetcas.v1.LfsBatchObject.ActionsEntry
}
var file_xetcas_v1_bridge_proto_depIdxs = []int32{
	0, // 0: candace.xetcas.v1.LfsBatchRequest.ref:type_name -> candace.xetcas.v1.LfsRef
	1, // 1: candace.xetcas.v1.LfsBatchRequest.objects:type_name -> candace.xetcas.v1.LfsObjectSpec
	8, // 2: candace.xetcas.v1.LfsAction.header:type_name -> candace.xetcas.v1.LfsAction.HeaderEntry
	9, // 3: candace.xetcas.v1.LfsBatchObject.actions:type_name -> candace.xetcas.v1.LfsBatchObject.ActionsEntry
	4, // 4: candace.xetcas.v1.LfsBatchObject.error:type_name -> candace.xetcas.v1.LfsObjectError
	5, // 5: candace.xetcas.v1.LfsBatchResponse.objects:type_name -> candace.xetcas.v1.LfsBatchObject
	3, // 6: candace.xetcas.v1.LfsBatchObject.ActionsEntry.value:type_name -> candace.xetcas.v1.LfsAction
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_xetcas_v1_bridge_proto_init() }
func file_xetcas_v1_bridge_proto_init() {
	if File_xetcas_v1_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xetcas_v1_bridge_proto_rawDesc), len(file_xetcas_v1_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xetcas_v1_bridge_proto_goTypes,
		DependencyIndexes: file_xetcas_v1_bridge_proto_depIdxs,
		MessageInfos:      file_xetcas_v1_bridge_proto_msgTypes,
	}.Build()
	File_xetcas_v1_bridge_proto = out.File
	file_xetcas_v1_bridge_proto_goTypes = nil
	file_xetcas_v1_bridge_proto_depIdxs = nil
}
