// Storage contracts for the Xet CAS server: the metadata a server persists
// after parsing the binary artifacts the client uploads.
//
// The blobs themselves are stored verbatim-plus-footer: an uploaded xorb
// arrives as bare chunk frames (no footer); the server verifies it, appends
// the canonical xet-core V1 footer, and stores the result. Chunk frames stay
// at their original offsets from byte 0, so every url_range handed out by
// the transfer contract indexes the stored object directly.
//
// These records are encoded with prost's deterministic encoding and stored
// as single-row blobs in the server's index database, keyed by their hash.
// They deliberately contain no maps (map ordering would break deterministic
// encoding) and no floating point. Schema evolution follows proto rules:
// never reuse or renumber fields.
//
// The chunk-level global-deduplication index is NOT a proto blob: it is a
// relational table (chunk_hash -> xorb_hash, chunk_index) because it is
// queried by key, not read whole. Only dedup-eligible chunk hashes are
// indexed: a chunk is eligible when hash % 1024 == 0 (the modulus applies to
// the fourth u64 of the hash, little-endian — xet-core's convention) or when
// it starts a file, or when its shard entry carries the global-dedup flag
// (bit 31).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: xetcas/v1/storage.proto

package xetcasv1

import (
	_ "github.com/candacelabs/candacelib/liquidproto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// XorbRecord is the per-xorb index entry, derived by parsing and verifying
// an uploaded xorb body. Offsets use xet-core's conventions: entry k is the
// cumulative end offset of chunk k, so chunk k spans
// [k == 0 ? 0 : offsets[k-1], offsets[k]).
type XorbRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Xorb hash in xet-core hex form (64 lowercase hex chars; per-u64
	// little-endian groups, not plain byte-order hex).
	XorbHash string `protobuf:"bytes,1,opt,name=xorb_hash,json=xorbHash,proto3" json:"xorb_hash,omitempty"`
	// Number of chunk frames. A xorb holds at most 8192 chunks.
	NumChunks uint32 `protobuf:"varint,2,opt,name=num_chunks,json=numChunks,proto3" json:"num_chunks,omitempty"`
	// Byte length of the chunk-frame region of the stored object (the region
	// fetch URLs index into). The at-rest footer begins at this offset.
	FramesLength uint64 `protobuf:"varint,3,opt,name=frames_length,json=framesLength,proto3" json:"frames_length,omitempty"`
	// Total uncompressed content length; a xorb holds at most 64 MiB.
	UnpackedLength uint64 `protobuf:"varint,4,opt,name=unpacked_length,json=unpackedLength,proto3" json:"unpacked_length,omitempty"`
	// Cumulative physical end offset of each chunk frame (header included),
	// one entry per chunk; the last equals frames_length.
	ChunkBoundaryOffsets []uint32 `protobuf:"varint,5,rep,packed,name=chunk_boundary_offsets,json=chunkBoundaryOffsets,proto3" json:"chunk_boundary_offsets,omitempty"`
	// Cumulative uncompressed end offset of each chunk, one entry per chunk;
	// the last equals unpacked_length.
	UnpackedChunkOffsets []uint32 `protobuf:"varint,6,rep,packed,name=unpacked_chunk_offsets,json=unpackedChunkOffsets,proto3" json:"unpacked_chunk_offsets,omitempty"`
	// Raw 32-byte chunk hashes concatenated in chunk order (32 * num_chunks
	// bytes, xet-core memory order). Needed to build keyed dedup shards and to
	// verify shard verification entries.
	ChunkHashes []byte `protobuf:"bytes,7,opt,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"`
	// Unix seconds when the xorb was first stored.
	CreatedAt     uint64 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XorbRecord) Reset() {
	*x = XorbRecord{}
	mi := &file_xetcas_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XorbRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XorbRecord) ProtoMessage() {}

func (x *XorbRecord) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XorbRecord.ProtoReflect.Descriptor instead.
func (*XorbRecord) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_storage_proto_rawDescGZIP(), []int{0}
}

func (x *XorbRecord) GetXorbHash() string {
	if x != nil {
		return x.XorbHash
	}
	return ""
}

func (x *XorbRecord) GetNumChunks() uint32 {
	if x != nil {
		return x.NumChunks
	}
	return 0
}

func (x *XorbRecord) GetFramesLength() uint64 {
	if x != nil {
		return x.FramesLength
	}
	return 0
}

func (x *XorbRecord) GetUnpackedLength() uint64 {
	if x != nil {
		return x.UnpackedLength
	}
	return 0
}

func (x *XorbRecord) GetChunkBoundaryOffsets() []uint32 {
	if x != nil {
		return x.ChunkBoundaryOffsets
	}
	return nil
}

func (x *XorbRecord) GetUnpackedChunkOffsets() []uint32 {
	if x != nil {
		return x.UnpackedChunkOffsets
	}
	return nil
}

func (x *XorbRecord) GetChunkHashes() []byte {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

func (x *XorbRecord) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// FileTermRecord is one ordered reconstruction term of a stored file,
// mirroring a shard FileDataSequenceEntry.
type FileTermRecord struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	XorbHash string                 `protobuf:"bytes,1,opt,name=xorb_hash,json=xorbHash,proto3" json:"xorb_hash,omitempty"`
	// Chunk-index range within the xorb, end-exclusive.
	ChunkIndexStart uint32 `protobuf:"varint,2,opt,name=chunk_index_start,json=chunkIndexStart,proto3" json:"chunk_index_start,omitempty"`
	ChunkIndexEnd   uint32 `protobuf:"varint,3,opt,name=chunk_index_end,json=chunkIndexEnd,proto3" json:"chunk_index_end,omitempty"`
	// Uncompressed byte length this term contributes to the file.
	UnpackedSegmentBytes uint32 `protobuf:"varint,4,opt,name=unpacked_segment_bytes,json=unpackedSegmentBytes,proto3" json:"unpacked_segment_bytes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FileTermRecord) Reset() {
	*x = FileTermRecord{}
	mi := &file_xetcas_v1_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTermRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTermRecord) ProtoMessage() {}

func (x *FileTermRecord) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTermRecord.ProtoReflect.Descriptor instead.
func (*FileTermRecord) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_storage_proto_rawDescGZIP(), []int{1}
}

func (x *FileTermRecord) GetXorbHash() string {
	if x != nil {
		return x.XorbHash
	}
	return ""
}

func (x *FileTermRecord) GetChunkIndexStart() uint32 {
	if x != nil {
		return x.ChunkIndexStart
	}
	return 0
}

func (x *FileTermRecord) GetChunkIndexEnd() uint32 {
	if x != nil {
		return x.ChunkIndexEnd
	}
	return 0
}

func (x *FileTermRecord) GetUnpackedSegmentBytes() uint32 {
	if x != nil {
		return x.UnpackedSegmentBytes
	}
	return 0
}

// FileRecord is the per-file index entry, derived from an uploaded shard's
// file-info section.
type FileRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Xet file hash in xet-core hex form.
	FileHash string `protobuf:"bytes,1,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	// Total file length = sum of term unpacked_segment_bytes.
	FileLength uint64 `protobuf:"varint,2,opt,name=file_length,json=fileLength,proto3" json:"file_length,omitempty"`
	// SHA-256 of the file content in plain hex, from the shard's
	// FileMetadataExt when present, else empty. This is the linkage that lets
	// the LFS bridge serve downloads by git-lfs oid.
	Sha256 string `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// Ordered reconstruction terms.
	Terms []*FileTermRecord `protobuf:"bytes,4,rep,name=terms,proto3" json:"terms,omitempty"`
	// Raw 32-byte verification range hashes concatenated in term order
	// (32 * len(terms) bytes) when the shard carried verification entries,
	// else empty. range_hash = blake3_keyed(VERIFICATION_KEY,
	// concat(chunk hashes of the term's range)).
	VerificationRangeHashes []byte `protobuf:"bytes,5,opt,name=verification_range_hashes,json=verificationRangeHashes,proto3" json:"verification_range_hashes,omitempty"`
	// Unix seconds when the file record was first registered.
	CreatedAt     uint64 `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRecord) Reset() {
	*x = FileRecord{}
	mi := &file_xetcas_v1_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRecord) ProtoMessage() {}

func (x *FileRecord) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRecord.ProtoReflect.Descriptor instead.
func (*FileRecord) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_storage_proto_rawDescGZIP(), []int{2}
}

func (x *FileRecord) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *FileRecord) GetFileLength() uint64 {
	if x != nil {
		return x.FileLength
	}
	return 0
}

func (x *FileRecord) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *FileRecord) GetTerms() []*FileTermRecord {
	if x != nil {
		return x.Terms
	}
	return nil
}

func (x *FileRecord) GetVerificationRangeHashes() []byte {
	if x != nil {
		return x.VerificationRangeHashes
	}
	return nil
}

func (x *FileRecord) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_xetcas_v1_storage_proto protoreflect.FileDescriptor

const file_xetcas_v1_storage_proto_rawDesc = "" +
	"\n" +
	"\x17xetcas/v1/storage.proto\x12\x11candace.xetcas.v1\x1a\x1fliquidproto/v1/refinement.proto\"\xb7\x03\n" +
	"\n" +
	"XorbRecord\x12U\n" +
	"\txorb_hash\x18\x01 \x01(\tB8\x92\x82\x194\n" +
	"2len(this) == 64 && matches(this, \"^[0-9a-f]{64}$\")R\bxorbHash\x12>\n" +
	"\n" +
	"num_chunks\x18\x02 \x01(\rB\x1f\x92\x82\x19\x1b\n" +
	"\x19this >= 1 && this <= 8192R\tnumChunks\x12#\n" +
	"\rframes_length\x18\x03 \x01(\x04R\fframesLength\x12?\n" +
	"\x0funpacked_length\x18\x04 \x01(\x04B\x16\x92\x82\x19\x12\n" +
	"\x10this <= 67108864R\x0eunpackedLength\x124\n" +
	"\x16chunk_boundary_offsets\x18\x05 \x03(\rR\x14chunkBoundaryOffsets\x124\n" +
	"\x16unpacked_chunk_offsets\x18\x06 \x03(\rR\x14unpackedChunkOffsets\x12!\n" +
	"\fchunk_hashes\x18\a \x01(\fR\vchunkHashes\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x04R\tcreatedAt\"\xf1\x01\n" +
	"\x0eFileTermRecord\x12U\n" +
	"\txorb_hash\x18\x01 \x01(\tB8\x92\x82\x194\n" +
	"2len(this) == 64 && matches(this, \"^[0-9a-f]{64}$\")R\bxorbHash\x12*\n" +
	"\x11chunk_index_start\x18\x02 \x01(\rR\x0fchunkIndexStart\x12&\n" +
	"\x0fchunk_index_end\x18\x03 \x01(\rR\rchunkIndexEnd\x124\n" +
	"\x16unpacked_segment_bytes\x18\x04 \x01(\rR\x14unpackedSegmentBytes\"\xfe\x02\n" +
	"\n" +
	"FileRecord\x12U\n" +
	"\tfile_hash\x18\x01 \x01(\tB8\x92\x82\x194\n" +
	"2len(this) == 64 && matches(this, \"^[0-9a-f]{64}$\")R\bfileHash\x12\x1f\n" +
	"\vfile_length\x18\x02 \x01(\x04R\n" +
	"fileLength\x12d\n" +
	"\x06sha256\x18\x03 \x01(\tBL\x92\x82\x19H\n" +
	"Flen(this) == 0 || (len(this) == 64 && matches(this, \"^[0-9a-f]{64}$\"))R\x06sha256\x127\n" +
	"\x05terms\x18\x04 \x03(\v2!.candace.xetcas.v1.FileTermRecordR\x05terms\x12:\n" +
	"\x19verification_range_hashes\x18\x05 \x01(\fR\x17verificationRangeHashes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x04R\tcreatedAtB4Z2github.com/candacelabs/xetcas/go/xetcasv1;xetcasv1b\x06proto3"

var (
	file_xetcas_v1_storage_proto_rawDescOnce sync.Once
	file_xetcas_v1_storage_proto_rawDescData []byte
)

func file_xetcas_v1_storage_proto_rawDescGZIP() []byte {
	file_xetcas_v1_storage_proto_rawDescOnce.Do(func() {
		file_xetcas_v1_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xetcas_v1_storage_proto_rawDesc), len(file_xetcas_v1_storage_proto_rawDesc)))
	})
	return file_xetcas_v1_storage_proto_rawDescData
}

var file_xetcas_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_xetcas_v1_storage_proto_goTypes = []any{
	(*XorbRecord)(nil),     // 0: candace.xetcas.v1.XorbRecord
	(*FileTermRecord)(nil), // 1: candace.xetcas.v1.FileTermRecord
	(*FileRecord)(nil),     // 2: candace.xetcas.v1.FileRecord
}
var file_xetcas_v1_storage_proto_depIdxs = []int32{
	1, // 0: candace.xetcas.v1.FileRecord.terms:type_name -> candace.xetcas.v1.FileTermRecord
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_xetcas_v1_storage_proto_init() }
func file_xetcas_v1_storage_proto_init() {
	if File_xetcas_v1_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xetcas_v1_storage_proto_rawDesc), len(file_xetcas_v1_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xetcas_v1_storage_proto_goTypes,
		DependencyIndexes: file_xetcas_v1_storage_proto_depIdxs,
		MessageInfos:      file_xetcas_v1_storage_proto_msgTypes,
	}.Build()
	File_xetcas_v1_storage_proto = out.File
	file_xetcas_v1_storage_proto_goTypes = nil
	file_xetcas_v1_storage_proto_depIdxs = nil
}
