// Code generated by protoc-gen-liquidproto. DO NOT EDIT.
// versions:
// 	protoc-gen-liquidproto v0.1.0
// 	protoc                 v7.35.1
// source: xetcas/v1/storage.proto

package xetcasv1

import (
	fmt "fmt"
	liquidproto "github.com/candacelabs/candacelib/liquidproto"
	regexp "regexp"
)

var (
	_liquidXorbRecordXorbHashRe0     = regexp.MustCompile("^[0-9a-f]{64}$")
	_liquidFileTermRecordXorbHashRe0 = regexp.MustCompile("^[0-9a-f]{64}$")
	_liquidFileRecordFileHashRe0     = regexp.MustCompile("^[0-9a-f]{64}$")
	_liquidFileRecordSha256Re0       = regexp.MustCompile("^[0-9a-f]{64}$")
)

// ValidateXorbRecord validates Liquid Proto field predicates.
func ValidateXorbRecord(message *XorbRecord) error {
	if message == nil {
		return fmt.Errorf("ValidateXorbRecord: nil *XorbRecord")
	}
	if !(len(message.XorbHash) == 64 && _liquidXorbRecordXorbHashRe0.MatchString(message.XorbHash)) {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.XorbRecord",
			Field:     "xorb_hash",
			Predicate: "len(this) == 64 && matches(this, \"^[0-9a-f]{64}$\")",
			Value:     message.XorbHash,
		}
	}
	if !(message.NumChunks >= 1 && message.NumChunks <= 8192) {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.XorbRecord",
			Field:     "num_chunks",
			Predicate: "this >= 1 && this <= 8192",
			Value:     message.NumChunks,
		}
	}
	if !(message.UnpackedLength <= 67108864) {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.XorbRecord",
			Field:     "unpacked_length",
			Predicate: "this <= 67108864",
			Value:     message.UnpackedLength,
		}
	}
	return nil
}

// ValidateFileTermRecord validates Liquid Proto field predicates.
func ValidateFileTermRecord(message *FileTermRecord) error {
	if message == nil {
		return fmt.Errorf("ValidateFileTermRecord: nil *FileTermRecord")
	}
	if !(len(message.XorbHash) == 64 && _liquidFileTermRecordXorbHashRe0.MatchString(message.XorbHash)) {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.FileTermRecord",
			Field:     "xorb_hash",
			Predicate: "len(this) == 64 && matches(this, \"^[0-9a-f]{64}$\")",
			Value:     message.XorbHash,
		}
	}
	return nil
}

// ValidateFileRecord validates Liquid Proto field predicates.
func ValidateFileRecord(message *FileRecord) error {
	if message == nil {
		return fmt.Errorf("ValidateFileRecord: nil *FileRecord")
	}
	if !(len(message.FileHash) == 64 && _liquidFileRecordFileHashRe0.MatchString(message.FileHash)) {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.FileRecord",
			Field:     "file_hash",
			Predicate: "len(this) == 64 && matches(this, \"^[0-9a-f]{64}$\")",
			Value:     message.FileHash,
		}
	}
	if !(len(message.Sha256) == 0 || (len(message.Sha256) == 64 && _liquidFileRecordSha256Re0.MatchString(message.Sha256))) {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.FileRecord",
			Field:     "sha256",
			Predicate: "len(this) == 0 || (len(this) == 64 && matches(this, \"^[0-9a-f]{64}$\"))",
			Value:     message.Sha256,
		}
	}
	return nil
}
