// Code generated by protoc-gen-liquidproto. DO NOT EDIT.
// versions:
// 	protoc-gen-liquidproto v0.1.0
// 	protoc                 v7.35.1
// source: xetcas/v1/transfer.proto

package xetcasv1

import (
	fmt "fmt"
	liquidproto "github.com/candacelabs/candacelib/liquidproto"
	regexp "regexp"
)

var (
	_liquidQueryReconstructionRequestFileIdRe0 = regexp.MustCompile("^[0-9a-f]{64}$")
	_liquidCasReconstructionTermHashRe0        = regexp.MustCompile("^[0-9a-f]{64}$")
	_liquidChunkDedupQueryHashRe0              = regexp.MustCompile("^[0-9a-f]{64}$")
	_liquidUploadXorbKeyHashRe0                = regexp.MustCompile("^[0-9a-f]{64}$")
)

// ValidateQueryReconstructionRequest validates Liquid Proto field predicates.
func ValidateQueryReconstructionRequest(message *QueryReconstructionRequest) error {
	if message == nil {
		return fmt.Errorf("ValidateQueryReconstructionRequest: nil *QueryReconstructionRequest")
	}
	if !(len(message.FileId) == 64 && _liquidQueryReconstructionRequestFileIdRe0.MatchString(message.FileId)) {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.QueryReconstructionRequest",
			Field:     "file_id",
			Predicate: "len(this) == 64 && matches(this, \"^[0-9a-f]{64}$\")",
			Value:     message.FileId,
		}
	}
	return nil
}

// ValidateCasReconstructionTerm validates Liquid Proto field predicates.
func ValidateCasReconstructionTerm(message *CasReconstructionTerm) error {
	if message == nil {
		return fmt.Errorf("ValidateCasReconstructionTerm: nil *CasReconstructionTerm")
	}
	if !(len(message.Hash) == 64 && _liquidCasReconstructionTermHashRe0.MatchString(message.Hash)) {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.CasReconstructionTerm",
			Field:     "hash",
			Predicate: "len(this) == 64 && matches(this, \"^[0-9a-f]{64}$\")",
			Value:     message.Hash,
		}
	}
	return nil
}

// ValidateCasReconstructionFetchInfo validates Liquid Proto field predicates.
func ValidateCasReconstructionFetchInfo(message *CasReconstructionFetchInfo) error {
	if message == nil {
		return fmt.Errorf("ValidateCasReconstructionFetchInfo: nil *CasReconstructionFetchInfo")
	}
	if !(len(message.Url) >= 1) {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.CasReconstructionFetchInfo",
			Field:     "url",
			Predicate: "len(this) >= 1",
			Value:     message.Url,
		}
	}
	return nil
}

// ValidateXorbMultiRangeFetch validates Liquid Proto field predicates.
func ValidateXorbMultiRangeFetch(message *XorbMultiRangeFetch) error {
	if message == nil {
		return fmt.Errorf("ValidateXorbMultiRangeFetch: nil *XorbMultiRangeFetch")
	}
	if !(len(message.Url) >= 1) {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.XorbMultiRangeFetch",
			Field:     "url",
			Predicate: "len(this) >= 1",
			Value:     message.Url,
		}
	}
	return nil
}

// ValidateChunkDedupQuery validates Liquid Proto field predicates.
func ValidateChunkDedupQuery(message *ChunkDedupQuery) error {
	if message == nil {
		return fmt.Errorf("ValidateChunkDedupQuery: nil *ChunkDedupQuery")
	}
	if !(len(message.Prefix) >= 1) {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.ChunkDedupQuery",
			Field:     "prefix",
			Predicate: "len(this) >= 1",
			Value:     message.Prefix,
		}
	}
	if !(len(message.Hash) == 64 && _liquidChunkDedupQueryHashRe0.MatchString(message.Hash)) {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.ChunkDedupQuery",
			Field:     "hash",
			Predicate: "len(this) == 64 && matches(this, \"^[0-9a-f]{64}$\")",
			Value:     message.Hash,
		}
	}
	return nil
}

// ValidateUploadXorbKey validates Liquid Proto field predicates.
func ValidateUploadXorbKey(message *UploadXorbKey) error {
	if message == nil {
		return fmt.Errorf("ValidateUploadXorbKey: nil *UploadXorbKey")
	}
	if !(len(message.Prefix) >= 1) {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.UploadXorbKey",
			Field:     "prefix",
			Predicate: "len(this) >= 1",
			Value:     message.Prefix,
		}
	}
	if !(len(message.Hash) == 64 && _liquidUploadXorbKeyHashRe0.MatchString(message.Hash)) {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.UploadXorbKey",
			Field:     "hash",
			Predicate: "len(this) == 64 && matches(this, \"^[0-9a-f]{64}$\")",
			Value:     message.Hash,
		}
	}
	return nil
}

// ValidateUploadShardResponse validates Liquid Proto field predicates.
func ValidateUploadShardResponse(message *UploadShardResponse) error {
	if message == nil {
		return fmt.Errorf("ValidateUploadShardResponse: nil *UploadShardResponse")
	}
	if !(message.Result <= 1) {
		return &liquidproto.Error{
			Message:   "candace.xetcas.v1.UploadShardResponse",
			Field:     "result",
			Predicate: "this <= 1",
			Value:     message.Result,
		}
	}
	return nil
}
