// Transfer contracts for the Xet CAS storage/transfer protocol.
//
// These messages codify the HTTP surface a Xet CAS server must expose for the
// real xet-core client (github.com/huggingface/xet-core, rev 77fc84d3d), as
// specified by that repository's openapi/cas.openapi.yaml and confirmed
// against the client source. Storage and transfer only: authentication is a
// deployment concern outside this contract (the server accepts a bearer token
// but this schema does not model token issuance), and the fire-and-forget
// /v1/telemetry endpoint is deliberately not modeled — a server returns
// 200 and drops the body.
//
// Wire mapping. The transfer wire format is JSON; field names below match the
// wire byte-for-byte. Messages that appear as JSON map values wrapped in a
// single repeated field (FetchInfoList, XorbFetchList) MUST serialize as the
// bare array, not as an object — Rust codegen marks them #[serde(transparent)]
// and the Go boundary marshals the inner slice directly.
//
// Endpoints covered (all under the client-configured endpoint base URL):
//
//   GET  /v1/reconstructions/{file_id}   -> QueryReconstructionResponse
//   GET  /v2/reconstructions/{file_id}   -> QueryReconstructionResponseV2
//                                           (optional; 404/501 => client
//                                           falls back to v1 and caches that)
//   GET  /v1/chunks/{prefix}/{hash}      -> raw shard bytes (global dedup)
//   POST /v1/xorbs/{prefix}/{hash}       -> UploadXorbResponse
//   POST /v1/shards                      -> UploadShardResponse
//
// Xorb and shard request bodies are the xet-core binary serialization formats
// (application/octet-stream); their internal layout is xet-core's contract,
// not re-specified here. The storage.proto sibling schema codifies what a
// server persists after parsing them; bridge.proto codifies the Git LFS
// bridge that makes `git push` reach this surface.
//
// Semantics a conforming server must honor (research citations live in
// docs/research/):
//   - A ranged reconstruction whose start is at/past EOF answers 416, not
//     404 — the client uses 416 as its end-of-file discovery signal.
//   - Xorb and shard uploads are idempotent; re-uploads happen on retry and
//     resume. Any 200 is success.
//   - Xorb upload bodies arrive as chunked transfer WITH an explicit
//     Content-Length; accept both simultaneously.
//   - Dedup misses are 404. The client coerces every dedup error to a miss
//     and never retries; global dedup is best-effort by design.
//   - fetch_info URLs are fetched with NO Authorization header. Expired
//     URLs must answer 403 (the one status that triggers refresh+retry).
//   - The batch form GET /v1/reconstructions?file_id=... has no production
//     caller in xet-core and is deliberately not part of this contract.
//   - Authorization: Bearer and X-Xet-Session-Id request headers must be
//     accepted; a permissive deployment may ignore both.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: xetcas/v1/transfer.proto

package xetcasv1

import (
	_ "github.com/candacelabs/candacelib/liquidproto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IndexRange is a chunk-index range within a xorb, end-EXCLUSIVE: [start, end).
// Cross-field invariant (start < end for non-empty ranges) is enforced by the
// boundary validators; per-field refinements cannot express it.
type IndexRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint32                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           uint32                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRange) Reset() {
	*x = IndexRange{}
	mi := &file_xetcas_v1_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRange) ProtoMessage() {}

func (x *IndexRange) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRange.ProtoReflect.Descriptor instead.
func (*IndexRange) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *IndexRange) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *IndexRange) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

// ByteRange is a byte range, end-INCLUSIVE: [start, end], matching HTTP Range
// header semantics ("bytes={start}-{end}").
type ByteRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint64                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           uint64                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByteRange) Reset() {
	*x = ByteRange{}
	mi := &file_xetcas_v1_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByteRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByteRange) ProtoMessage() {}

func (x *ByteRange) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByteRange.ProtoReflect.Descriptor instead.
func (*ByteRange) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *ByteRange) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ByteRange) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

// QueryReconstructionRequest is the parsed form of
// GET /v1/reconstructions/{file_id} (and /v2/...).
type QueryReconstructionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File hash in hex: exactly 64 lowercase hexadecimal characters.
	FileId string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	// Optional byte range from the HTTP Range header (bytes={start}-{end},
	// end-inclusive). Absent means the whole file.
	Range         *ByteRange `protobuf:"bytes,2,opt,name=range,proto3,oneof" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryReconstructionRequest) Reset() {
	*x = QueryReconstructionRequest{}
	mi := &file_xetcas_v1_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryReconstructionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReconstructionRequest) ProtoMessage() {}

func (x *QueryReconstructionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReconstructionRequest.ProtoReflect.Descriptor instead.
func (*QueryReconstructionRequest) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *QueryReconstructionRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *QueryReconstructionRequest) GetRange() *ByteRange {
	if x != nil {
		return x.Range
	}
	return nil
}

// CasReconstructionTerm is one ordered term of a file reconstruction: take
// chunks [range.start, range.end) from the xorb named by hash.
type CasReconstructionTerm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Xorb hash in hex: exactly 64 lowercase hexadecimal characters.
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// Chunk-index range within the xorb, end-exclusive.
	Range *IndexRange `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	// Total unpacked (decompressed) byte length of the term's chunks. u32 on
	// the wire (xet_client cas_types); a term never exceeds one xorb's 64 MiB.
	UnpackedLength uint32 `protobuf:"varint,3,opt,name=unpacked_length,json=unpackedLength,proto3" json:"unpacked_length,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CasReconstructionTerm) Reset() {
	*x = CasReconstructionTerm{}
	mi := &file_xetcas_v1_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CasReconstructionTerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasReconstructionTerm) ProtoMessage() {}

func (x *CasReconstructionTerm) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasReconstructionTerm.ProtoReflect.Descriptor instead.
func (*CasReconstructionTerm) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *CasReconstructionTerm) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *CasReconstructionTerm) GetRange() *IndexRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *CasReconstructionTerm) GetUnpackedLength() uint32 {
	if x != nil {
		return x.UnpackedLength
	}
	return 0
}

// CasReconstructionFetchInfo tells the client how to fetch one chunk range of
// one xorb: issue GET {url} with "Range: bytes={url_range.start}-{url_range.end}"
// (end-inclusive) and treat the body as the serialized chunk frames covering
// chunk range [range.start, range.end). The URL may be any HTTP(S) URL,
// including one served by the same CAS server; it must remain valid for the
// duration of a client download session.
type CasReconstructionFetchInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         *IndexRange            `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	UrlRange      *ByteRange             `protobuf:"bytes,3,opt,name=url_range,json=urlRange,proto3" json:"url_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CasReconstructionFetchInfo) Reset() {
	*x = CasReconstructionFetchInfo{}
	mi := &file_xetcas_v1_transfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CasReconstructionFetchInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasReconstructionFetchInfo) ProtoMessage() {}

func (x *CasReconstructionFetchInfo) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_transfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasReconstructionFetchInfo.ProtoReflect.Descriptor instead.
func (*CasReconstructionFetchInfo) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_transfer_proto_rawDescGZIP(), []int{4}
}

func (x *CasReconstructionFetchInfo) GetRange() *IndexRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *CasReconstructionFetchInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CasReconstructionFetchInfo) GetUrlRange() *ByteRange {
	if x != nil {
		return x.UrlRange
	}
	return nil
}

// FetchInfoList is the JSON-transparent list wrapper for fetch_info map
// values: it serializes as the bare array of entries.
type FetchInfoList struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Entries       []*CasReconstructionFetchInfo `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchInfoList) Reset() {
	*x = FetchInfoList{}
	mi := &file_xetcas_v1_transfer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchInfoList) ProtoMessage() {}

func (x *FetchInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_transfer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchInfoList.ProtoReflect.Descriptor instead.
func (*FetchInfoList) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_transfer_proto_rawDescGZIP(), []int{5}
}

func (x *FetchInfoList) GetEntries() []*CasReconstructionFetchInfo {
	if x != nil {
		return x.Entries
	}
	return nil
}

// QueryReconstructionResponse is the v1 reconstruction body.
type QueryReconstructionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bytes to discard from the start of the first term before returning data
	// to the caller (nonzero only for ranged queries whose start falls inside
	// a chunk).
	OffsetIntoFirstRange uint64                   `protobuf:"varint,1,opt,name=offset_into_first_range,json=offsetIntoFirstRange,proto3" json:"offset_into_first_range,omitempty"`
	Terms                []*CasReconstructionTerm `protobuf:"bytes,2,rep,name=terms,proto3" json:"terms,omitempty"`
	// Map from xorb hash (64-char lowercase hex) to fetch entries for every
	// chunk range referenced by terms. Values serialize as bare JSON arrays.
	FetchInfo     map[string]*FetchInfoList `protobuf:"bytes,3,rep,name=fetch_info,json=fetchInfo,proto3" json:"fetch_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryReconstructionResponse) Reset() {
	*x = QueryReconstructionResponse{}
	mi := &file_xetcas_v1_transfer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryReconstructionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReconstructionResponse) ProtoMessage() {}

func (x *QueryReconstructionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_transfer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReconstructionResponse.ProtoReflect.Descriptor instead.
func (*QueryReconstructionResponse) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_transfer_proto_rawDescGZIP(), []int{6}
}

func (x *QueryReconstructionResponse) GetOffsetIntoFirstRange() uint64 {
	if x != nil {
		return x.OffsetIntoFirstRange
	}
	return 0
}

func (x *QueryReconstructionResponse) GetTerms() []*CasReconstructionTerm {
	if x != nil {
		return x.Terms
	}
	return nil
}

func (x *QueryReconstructionResponse) GetFetchInfo() map[string]*FetchInfoList {
	if x != nil {
		return x.FetchInfo
	}
	return nil
}

// XorbRangeDescriptor pairs a chunk range with the byte range it occupies in
// the stored (serialized) xorb.
type XorbRangeDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        *IndexRange            `protobuf:"bytes,1,opt,name=chunks,proto3" json:"chunks,omitempty"`
	Bytes         *ByteRange             `protobuf:"bytes,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XorbRangeDescriptor) Reset() {
	*x = XorbRangeDescriptor{}
	mi := &file_xetcas_v1_transfer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XorbRangeDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XorbRangeDescriptor) ProtoMessage() {}

func (x *XorbRangeDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_transfer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XorbRangeDescriptor.ProtoReflect.Descriptor instead.
func (*XorbRangeDescriptor) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_transfer_proto_rawDescGZIP(), []int{7}
}

func (x *XorbRangeDescriptor) GetChunks() *IndexRange {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *XorbRangeDescriptor) GetBytes() *ByteRange {
	if x != nil {
		return x.Bytes
	}
	return nil
}

// XorbMultiRangeFetch is one signed multi-range fetch entry of the v2
// reconstruction response. The client sends exactly the byte ranges listed,
// as one multi-range HTTP Range header, against url.
type XorbMultiRangeFetch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Url   string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Ranges covered by this URL, sorted ascending by chunks.start.
	Ranges        []*XorbRangeDescriptor `protobuf:"bytes,2,rep,name=ranges,proto3" json:"ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XorbMultiRangeFetch) Reset() {
	*x = XorbMultiRangeFetch{}
	mi := &file_xetcas_v1_transfer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XorbMultiRangeFetch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XorbMultiRangeFetch) ProtoMessage() {}

func (x *XorbMultiRangeFetch) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_transfer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XorbMultiRangeFetch.ProtoReflect.Descriptor instead.
func (*XorbMultiRangeFetch) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_transfer_proto_rawDescGZIP(), []int{8}
}

func (x *XorbMultiRangeFetch) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *XorbMultiRangeFetch) GetRanges() []*XorbRangeDescriptor {
	if x != nil {
		return x.Ranges
	}
	return nil
}

// XorbFetchList is the JSON-transparent list wrapper for the v2 xorbs map
// values: it serializes as the bare array of entries.
type XorbFetchList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*XorbMultiRangeFetch `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XorbFetchList) Reset() {
	*x = XorbFetchList{}
	mi := &file_xetcas_v1_transfer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XorbFetchList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XorbFetchList) ProtoMessage() {}

func (x *XorbFetchList) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_transfer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XorbFetchList.ProtoReflect.Descriptor instead.
func (*XorbFetchList) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_transfer_proto_rawDescGZIP(), []int{9}
}

func (x *XorbFetchList) GetEntries() []*XorbMultiRangeFetch {
	if x != nil {
		return x.Entries
	}
	return nil
}

// QueryReconstructionResponseV2 is the v2 (multi-range optimized) body.
// Servers may omit v2 entirely; clients fall back to v1 on 404/501.
type QueryReconstructionResponseV2 struct {
	state                protoimpl.MessageState   `protogen:"open.v1"`
	OffsetIntoFirstRange uint64                   `protobuf:"varint,1,opt,name=offset_into_first_range,json=offsetIntoFirstRange,proto3" json:"offset_into_first_range,omitempty"`
	Terms                []*CasReconstructionTerm `protobuf:"bytes,2,rep,name=terms,proto3" json:"terms,omitempty"`
	// Map from xorb hash to multi-range fetch entries (bare JSON arrays).
	Xorbs         map[string]*XorbFetchList `protobuf:"bytes,3,rep,name=xorbs,proto3" json:"xorbs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryReconstructionResponseV2) Reset() {
	*x = QueryReconstructionResponseV2{}
	mi := &file_xetcas_v1_transfer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryReconstructionResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReconstructionResponseV2) ProtoMessage() {}

func (x *QueryReconstructionResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_transfer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReconstructionResponseV2.ProtoReflect.Descriptor instead.
func (*QueryReconstructionResponseV2) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_transfer_proto_rawDescGZIP(), []int{10}
}

func (x *QueryReconstructionResponseV2) GetOffsetIntoFirstRange() uint64 {
	if x != nil {
		return x.OffsetIntoFirstRange
	}
	return 0
}

func (x *QueryReconstructionResponseV2) GetTerms() []*CasReconstructionTerm {
	if x != nil {
		return x.Terms
	}
	return nil
}

func (x *QueryReconstructionResponseV2) GetXorbs() map[string]*XorbFetchList {
	if x != nil {
		return x.Xorbs
	}
	return nil
}

// ChunkDedupQuery is the parsed form of GET /v1/chunks/{prefix}/{hash}: the
// global-deduplication probe. A hit returns raw shard bytes
// (application/octet-stream) whose cas-info section names the xorb containing
// the chunk; a miss is 404.
type ChunkDedupQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prefix path segment. The OpenAPI spec documents "default-merkledb" here,
	// but the real client sends its configured default prefix ("default") for
	// both this route and xorb upload — servers accept any non-empty prefix.
	Prefix        string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Hash          string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkDedupQuery) Reset() {
	*x = ChunkDedupQuery{}
	mi := &file_xetcas_v1_transfer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkDedupQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkDedupQuery) ProtoMessage() {}

func (x *ChunkDedupQuery) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_transfer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkDedupQuery.ProtoReflect.Descriptor instead.
func (*ChunkDedupQuery) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_transfer_proto_rawDescGZIP(), []int{11}
}

func (x *ChunkDedupQuery) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ChunkDedupQuery) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// UploadXorbKey is the parsed form of POST /v1/xorbs/{prefix}/{hash} path
// parameters. The request body is the xet-core serialized xorb; the server
// must verify the body's computed xorb hash equals hash before storing.
type UploadXorbKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prefix path segment; the client sends "default". Accept any non-empty
	// prefix (see ChunkDedupQuery.prefix).
	Prefix        string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Hash          string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadXorbKey) Reset() {
	*x = UploadXorbKey{}
	mi := &file_xetcas_v1_transfer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadXorbKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadXorbKey) ProtoMessage() {}

func (x *UploadXorbKey) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_transfer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadXorbKey.ProtoReflect.Descriptor instead.
func (*UploadXorbKey) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_transfer_proto_rawDescGZIP(), []int{12}
}

func (x *UploadXorbKey) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *UploadXorbKey) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// UploadXorbResponse is the JSON body answering a xorb upload.
type UploadXorbResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// false when the xorb already existed; the upload is idempotent either way.
	WasInserted   bool `protobuf:"varint,1,opt,name=was_inserted,json=wasInserted,proto3" json:"was_inserted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadXorbResponse) Reset() {
	*x = UploadXorbResponse{}
	mi := &file_xetcas_v1_transfer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadXorbResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadXorbResponse) ProtoMessage() {}

func (x *UploadXorbResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_transfer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadXorbResponse.ProtoReflect.Descriptor instead.
func (*UploadXorbResponse) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_transfer_proto_rawDescGZIP(), []int{13}
}

func (x *UploadXorbResponse) GetWasInserted() bool {
	if x != nil {
		return x.WasInserted
	}
	return false
}

// UploadShardResponse is the JSON body answering POST /v1/shards.
// result follows xet-core's numeric convention: 0 = shard already exists,
// 1 = sync performed (registered). Clients treat any 200 as success.
type UploadShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        uint32                 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadShardResponse) Reset() {
	*x = UploadShardResponse{}
	mi := &file_xetcas_v1_transfer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadShardResponse) ProtoMessage() {}

func (x *UploadShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xetcas_v1_transfer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadShardResponse.ProtoReflect.Descriptor instead.
func (*UploadShardResponse) Descriptor() ([]byte, []int) {
	return file_xetcas_v1_transfer_proto_rawDescGZIP(), []int{14}
}

func (x *UploadShardResponse) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_xetcas_v1_transfer_proto protoreflect.FileDescriptor

const file_xetcas_v1_transfer_proto_rawDesc = "" +
	"\n" +
	"\x18xetcas/v1/transfer.proto\x12\x11candace.xetcas.v1\x1a\x1fliquidproto/v1/refinement.proto\"4\n" +
	"\n" +
	"IndexRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\rR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\rR\x03end\"3\n" +
	"\tByteRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x04R\x03end\"\xb2\x01\n" +
	"\x1aQueryReconstructionRequest\x12Q\n" +
	"\afile_id\x18\x01 \x01(\tB8\x92\x82\x194\n" +
	"2len(this) == 64 && matches(this, \"^[0-9a-f]{64}$\")R\x06fileId\x127\n" +
	"\x05range\x18\x02 \x01(\v2\x1c.candace.xetcas.v1.ByteRangeH\x00R\x05range\x88\x01\x01B\b\n" +
	"\x06_range\"\xc3\x01\n" +
	"\x15CasReconstructionTerm\x12L\n" +
	"\x04hash\x18\x01 \x01(\tB8\x92\x82\x194\n" +
	"2len(this) == 64 && matches(this, \"^[0-9a-f]{64}$\")R\x04hash\x123\n" +
	"\x05range\x18\x02 \x01(\v2\x1d.candace.xetcas.v1.IndexRangeR\x05range\x12'\n" +
	"\x0funpacked_length\x18\x03 \x01(\rR\x0eunpackedLength\"\xb4\x01\n" +
	"\x1aCasReconstructionFetchInfo\x123\n" +
	"\x05range\x18\x01 \x01(\v2\x1d.candace.xetcas.v1.IndexRangeR\x05range\x12&\n" +
	"\x03url\x18\x02 \x01(\tB\x14\x92\x82\x19\x10\n" +
	"\x0elen(this) >= 1R\x03url\x129\n" +
	"\turl_range\x18\x03 \x01(\v2\x1c.candace.xetcas.v1.ByteRangeR\burlRange\"X\n" +
	"\rFetchInfoList\x12G\n" +
	"\aentries\x18\x01 \x03(\v2-.candace.xetcas.v1.CasReconstructionFetchInfoR\aentries\"\xd2\x02\n" +
	"\x1bQueryReconstructionResponse\x125\n" +
	"\x17offset_into_first_range\x18\x01 \x01(\x04R\x14offsetIntoFirstRange\x12>\n" +
	"\x05terms\x18\x02 \x03(\v2(.candace.xetcas.v1.CasReconstructionTermR\x05terms\x12\\\n" +
	"\n" +
	"fetch_info\x18\x03 \x03(\v2=.candace.xetcas.v1.QueryReconstructionResponse.FetchInfoEntryR\tfetchInfo\x1a^\n" +
	"\x0eFetchInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .candace.xetcas.v1.FetchInfoListR\x05value:\x028\x01\"\x80\x01\n" +
	"\x13XorbRangeDescriptor\x125\n" +
	"\x06chunks\x18\x01 \x01(\v2\x1d.candace.xetcas.v1.IndexRangeR\x06chunks\x122\n" +
	"\x05bytes\x18\x02 \x01(\v2\x1c.candace.xetcas.v1.ByteRangeR\x05bytes\"}\n" +
	"\x13XorbMultiRangeFetch\x12&\n" +
	"\x03url\x18\x01 \x01(\tB\x14\x92\x82\x19\x10\n" +
	"\x0elen(this) >= 1R\x03url\x12>\n" +
	"\x06ranges\x18\x02 \x03(\v2&.candace.xetcas.v1.XorbRangeDescriptorR\x06ranges\"Q\n" +
	"\rXorbFetchList\x12@\n" +
	"\aentries\x18\x01 \x03(\v2&.candace.xetcas.v1.XorbMultiRangeFetchR\aentries\"\xc5\x02\n" +
	"\x1dQueryReconstructionResponseV2\x125\n" +
	"\x17offset_into_first_range\x18\x01 \x01(\x04R\x14offsetIntoFirstRange\x12>\n" +
	"\x05terms\x18\x02 \x03(\v2(.candace.xetcas.v1.CasReconstructionTermR\x05terms\x12Q\n" +
	"\x05xorbs\x18\x03 \x03(\v2;.candace.xetcas.v1.QueryReconstructionResponseV2.XorbsEntryR\x05xorbs\x1aZ\n" +
	"\n" +
	"XorbsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .candace.xetcas.v1.XorbFetchListR\x05value:\x028\x01\"\x8d\x01\n" +
	"\x0fChunkDedupQuery\x12,\n" +
	"\x06prefix\x18\x01 \x01(\tB\x14\x92\x82\x19\x10\n" +
	"\x0elen(this) >= 1R\x06prefix\x12L\n" +
	"\x04hash\x18\x02 \x01(\tB8\x92\x82\x194\n" +
	"2len(this) == 64 && matches(this, \"^[0-9a-f]{64}$\")R\x04hash\"\x8b\x01\n" +
	"\rUploadXorbKey\x12,\n" +
	"\x06prefix\x18\x01 \x01(\tB\x14\x92\x82\x19\x10\n" +
	"\x0elen(this) >= 1R\x06prefix\x12L\n" +
	"\x04hash\x18\x02 \x01(\tB8\x92\x82\x194\n" +
	"2len(this) == 64 && matches(this, \"^[0-9a-f]{64}$\")R\x04hash\"7\n" +
	"\x12UploadXorbResponse\x12!\n" +
	"\fwas_inserted\x18\x01 \x01(\bR\vwasInserted\">\n" +
	"\x13UploadShardResponse\x12'\n" +
	"\x06result\x18\x01 \x01(\rB\x0f\x92\x82\x19\v\n" +
	"\tthis <= 1R\x06resultB4Z2github.com/candacelabs/xetcas/go/xetcasv1;xetcasv1b\x06proto3"

var (
	file_xetcas_v1_transfer_proto_rawDescOnce sync.Once
	file_xetcas_v1_transfer_proto_rawDescData []byte
)

func file_xetcas_v1_transfer_proto_rawDescGZIP() []byte {
	file_xetcas_v1_transfer_proto_rawDescOnce.Do(func() {
		file_xetcas_v1_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xetcas_v1_transfer_proto_rawDesc), len(file_xetcas_v1_transfer_proto_rawDesc)))
	})
	return file_xetcas_v1_transfer_proto_rawDescData
}

var file_xetcas_v1_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_xetcas_v1_transfer_proto_goTypes = []any{
	(*IndexRange)(nil),                    // 0: candace.xetcas.v1.IndexRange
	(*ByteRange)(nil),                     // 1: candace.xetcas.v1.ByteRange
	(*QueryReconstructionRequest)(nil),    // 2: candace.xetcas.v1.QueryReconstructionRequest
	(*CasReconstructionTerm)(nil),         // 3: candace.xetcas.v1.CasReconstructionTerm
	(*CasReconstructionFetchInfo)(nil),    // 4: candace.xetcas.v1.CasReconstructionFetchInfo
	(*FetchInfoList)(nil),                 // 5: candace.xetcas.v1.FetchInfoList
	(*QueryReconstructionResponse)(nil),   // 6: candace.xetcas.v1.QueryReconstructionResponse
	(*XorbRangeDescriptor)(nil),           // 7: candace.xetcas.v1.XorbRangeDescriptor
	(*XorbMultiRangeFetch)(nil),           // 8: candace.xetcas.v1.XorbMultiRangeFetch
	(*XorbFetchList)(nil),                 // 9: candace.xetcas.v1.XorbFetchList
	(*QueryReconstructionResponseV2)(nil), // 10: candace.xetcas.v1.QueryReconstructionResponseV2
	(*ChunkDedupQuery)(nil),               // 11: candace.xetcas.v1.ChunkDedupQuery
	(*UploadXorbKey)(nil),                 // 12: candace.xetcas.v1.UploadXorbKey
	(*UploadXorbResponse)(nil),            // 13: candace.xetcas.v1.UploadXorbResponse
	(*UploadShardResponse)(nil),           // 14: candace.xetcas.v1.UploadShardResponse
	nil,                                   // 15: candace.xetcas.v1.QueryReconstructionResponse.FetchInfoEntry
	nil,                                   // 16: candace.xetcas.v1.QueryReconstructionResponseV2.XorbsEntry
}
var file_xetcas_v1_transfer_proto_depIdxs = []int32{
	1,  // 0: candace.xetcas.v1.QueryReconstructionRequest.range:type_name -> candace.xetcas.v1.ByteRange
	0,  // 1: candace.xetcas.v1.CasReconstructionTerm.range:type_name -> candace.xetcas.v1.IndexRange
	0,  // 2: candace.xetcas.v1.CasReconstructionFetchInfo.range:type_name -> candace.xetcas.v1.IndexRange
	1,  // 3: candace.xetcas.v1.CasReconstructionFetchInfo.url_range:type_name -> candace.xetcas.v1.ByteRange
	4,  // 4: candace.xetcas.v1.FetchInfoList.entries:type_name -> candace.xetcas.v1.CasReconstructionFetchInfo
	3,  // 5: candace.xetcas.v1.QueryReconstructionResponse.terms:type_name -> candace.xetcas.v1.CasReconstructionTerm
	15, // 6: candace.xetcas.v1.QueryReconstructionResponse.fetch_info:type_name -> candace.xetcas.v1.QueryReconstructionResponse.FetchInfoEntry
	0,  // 7: candace.xetcas.v1.XorbRangeDescriptor.chunks:type_name -> candace.xetcas.v1.IndexRange
	1,  // 8: candace.xetcas.v1.XorbRangeDescriptor.bytes:type_name -> candace.xetcas.v1.ByteRange
	7,  // 9: candace.xetcas.v1.XorbMultiRangeFetch.ranges:type_name -> candace.xetcas.v1.XorbRangeDescriptor
	8,  // 10: candace.xetcas.v1.XorbFetchList.entries:type_name -> candace.xetcas.v1.XorbMultiRangeFetch
	3,  // 11: candace.xetcas.v1.QueryReconstructionResponseV2.terms:type_name -> candace.xetcas.v1.CasReconstructionTerm
	16, // 12: candace.xetcas.v1.QueryReconstructionResponseV2.xorbs:type_name -> candace.xetcas.v1.QueryReconstructionResponseV2.XorbsEntry
	5,  // 13: candace.xetcas.v1.QueryReconstructionResponse.FetchInfoEntry.value:type_name -> candace.xetcas.v1.FetchInfoList
	9,  // 14: candace.xetcas.v1.QueryReconstructionResponseV2.XorbsEntry.value:type_name -> candace.xetcas.v1.XorbFetchList
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_xetcas_v1_transfer_proto_init() }
func file_xetcas_v1_transfer_proto_init() {
	if File_xetcas_v1_transfer_proto != nil {
		return
	}
	file_xetcas_v1_transfer_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xetcas_v1_transfer_proto_rawDesc), len(file_xetcas_v1_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xetcas_v1_transfer_proto_goTypes,
		DependencyIndexes: file_xetcas_v1_transfer_proto_depIdxs,
		MessageInfos:      file_xetcas_v1_transfer_proto_msgTypes,
	}.Build()
	File_xetcas_v1_transfer_proto = out.File
	file_xetcas_v1_transfer_proto_goTypes = nil
	file_xetcas_v1_transfer_proto_depIdxs = nil
}
